In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

In [3]:
n_pointer = 50

In [4]:
class_0 = np.random.randn(n_pointer, 2) * 0.7 + np.array([-2, -2])
class_0

array([[-1.65230009, -2.09678501],
       [-1.54661802, -0.9338791 ],
       [-2.16390736, -2.16389587],
       [-0.89455103, -1.46279569],
       [-2.32863207, -1.62020797],
       [-2.32439238, -2.32601083],
       [-1.83062641, -3.33929617],
       [-3.20744248, -2.39360127],
       [-2.70898178, -1.78002687],
       [-2.63561685, -2.98861259],
       [-0.97404586, -2.15804341],
       [-1.95273026, -2.99732373],
       [-2.38106791, -1.92235419],
       [-2.8056955 , -1.73701139],
       [-2.42044708, -2.20418562],
       [-2.42119463, -0.70340527],
       [-2.00944806, -2.74039765],
       [-1.42421856, -2.85459055],
       [-1.85379548, -3.37176909],
       [-2.92973023, -1.86219713],
       [-1.48307339, -1.8800422 ],
       [-2.0809538 , -2.21077259],
       [-3.03496539, -2.50389095],
       [-2.32244714, -1.26001444],
       [-1.7594672 , -3.23412811],
       [-1.77314122, -2.2695576 ],
       [-2.4738454 , -1.5718266 ],
       [-1.27830033, -1.34810392],
       [-2.58745227,

In [5]:
class_1 = np.random.randn(n_pointer, 2) * 0.7 + np.array([2, 2])
class_1

array([[1.00924048, 1.70554827],
       [1.76009984, 1.43840591],
       [1.8871    , 2.2828356 ],
       [3.32033013, 2.12220447],
       [2.18028527, 1.94788786],
       [0.65686015, 1.98144029],
       [2.04216115, 3.72426948],
       [1.86534732, 2.21108314],
       [1.97570176, 1.18192537],
       [2.79997597, 2.52635312],
       [2.55372236, 1.36342878],
       [2.98195602, 1.01870426],
       [2.41079997, 3.53331894],
       [1.30662457, 1.60359159],
       [2.06975596, 1.64756704],
       [0.9145356 , 2.04799408],
       [1.2563874 , 2.3315147 ],
       [1.35640304, 3.08495408],
       [1.4517227 , 1.77455694],
       [2.56946205, 1.13839498],
       [2.15922195, 2.91499993],
       [0.87476174, 2.1292437 ],
       [2.18191796, 2.54727601],
       [1.1341345 , 1.07568037],
       [2.3653591 , 2.20788927],
       [2.175345  , 2.24251375],
       [1.52398269, 2.16257759],
       [2.20515073, 1.49995401],
       [3.30604216, 2.33168304],
       [1.16608755, 2.45958753],
       [1.

In [7]:
X = np.vstack((class_0, class_1))
X

array([[-1.65230009, -2.09678501],
       [-1.54661802, -0.9338791 ],
       [-2.16390736, -2.16389587],
       [-0.89455103, -1.46279569],
       [-2.32863207, -1.62020797],
       [-2.32439238, -2.32601083],
       [-1.83062641, -3.33929617],
       [-3.20744248, -2.39360127],
       [-2.70898178, -1.78002687],
       [-2.63561685, -2.98861259],
       [-0.97404586, -2.15804341],
       [-1.95273026, -2.99732373],
       [-2.38106791, -1.92235419],
       [-2.8056955 , -1.73701139],
       [-2.42044708, -2.20418562],
       [-2.42119463, -0.70340527],
       [-2.00944806, -2.74039765],
       [-1.42421856, -2.85459055],
       [-1.85379548, -3.37176909],
       [-2.92973023, -1.86219713],
       [-1.48307339, -1.8800422 ],
       [-2.0809538 , -2.21077259],
       [-3.03496539, -2.50389095],
       [-2.32244714, -1.26001444],
       [-1.7594672 , -3.23412811],
       [-1.77314122, -2.2695576 ],
       [-2.4738454 , -1.5718266 ],
       [-1.27830033, -1.34810392],
       [-2.58745227,

In [8]:
y = np.array([0]*n_pointer + [1]*n_pointer)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
df = pd.DataFrame(X, columns=["x1", "x2"])
df["target"] = y

In [12]:
df.head(10)

,x1,x2,target
0,-1.652300,-2.096785,0
1,-1.546618,-0.933879,0
2,-2.163907,-2.163896,0
3,-0.894551,-1.462796,0
4,-2.328632,-1.620208,0
5,-2.324392,-2.326011,0
6,-1.830626,-3.339296,0
7,-3.207442,-2.393601,0
8,-2.708982,-1.780027,0
9,-2.635617,-2.988613,0


In [13]:
df.tail(10)

,x1,x2,target
90,2.437967,1.399990,1
91,1.250375,2.337731,1
92,1.843576,2.499800,1
93,2.331266,1.949020,1
94,1.407244,0.939607,1
95,1.687440,2.599479,1
96,2.149866,1.127983,1
97,2.121227,2.269722,1
98,1.381300,2.107608,1
99,2.040746,1.199921,1


In [14]:
plt.figure(figsize=(6, 5))
plt.scatter(df[df["target"]==0]["x1"],
           df[df["target"]==0]["x2"],
            label="Class 0")
plt.scatter(df[df["target"]==1]["x1"],
           df[df["target"]==1]["x2"],
            label="Class 1")
plt.xlabel("x1")
plt.ylabel("x2")
plt.title("Synthetic Linearly Separable Dataset")
plt.grid(True)


KeyError: 'ta'

<Figure size 600x500 with 0 Axes>